AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Style/NumericPredicate:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Copyright:
  Enabled: true
  Notice: 'Copyright:: .*20\d{2} Couchbase, Inc.'
  AutocorrectNotice: '# Copyright:: 20\d{2} Couchbase, Inc.'

Style/MutableConstant:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '()'
    '%w': '()'
    '%W': '()'
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Style/SafeNavigation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: lambda

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true
